clangNN (all versions): Remove PREFERRED_PROVIDER settings
Due to some changes in Yocto, some recipes started to exhibit weird
problems, like this for many build stages:

ERROR: When reparsing .../layers/meta-clang/recipes-devtools/clang/libclc_git.bb:do_configure,
the basehash value changed from d470bbf1de1644b65ac8fb6e2c63958e11fca0bf5c4c218a896263d3921957d9
to 5583c4ad183c62f34453be835257553c4217c24456e052c26bf0272258c32546.
The metadata is not deterministic and this needs to be fixed.
ERROR: The following commands may help:
ERROR: $ bitbake libclc -cdo_configure -Snone
ERROR: Then:
ERROR: $ bitbake libclc -cdo_configure -Sprintdiff

Remove PREFERRED_PROVIDER from clang.inc because apparently this
causes the problem. Also, it may have caused the dependency mixup
with some recipes pulling in both clang and clang14 or some other
combination of clang* packages.

Signed-off-by: Zoltán Böszörményi <zboszor@gmail.com>